version: '3'
services:
  app_test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - NODE_ENV=test
      - DB_HOST=db_test
      - DB_USER=postgres
      - DB_PASSWORD=example
      - DB_NAME=job_platform_test
      - DB_PORT=5432
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      db_test:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
    networks:
      - job-network
    command: npm test

  db_test:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: job_platform_test
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    networks:
      - job-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d job_platform_test"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  job-network:

volumes:
  pgdata_test:
